### ISSUE TITLE
Roadmap to stable version

### ISSUE THREAD

**Issue by bregydoc** [minskylab/plexo-core#9]
- [ ] Fully support for subscriptions
- [ ] Stable methods for authorization and authentication
- [ ] PostgreSQL automated Migrations
- [ ] Better decouple between `plexo-platform` and `plexo-core`
